version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo_container
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  backend:
    image: riyaji/news_hub_backend:${BUILD_NUMBER}
    container_name: backend_container
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    env_file:
      - ./backend/.env

  frontend:
    image: riyaji/news_hub_frontend:${BUILD_NUMBER}
    container_name: frontend_container
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  mongo_data:
